24 UI 34 implement new link component
hack-the-6ix/react-ui pull request #27
Opened 2023-05-04 18:49 UTC by whyismynamerudy

Added the necessary component. Some notes:

- added textType prop to support the Typography component
- added a target prop

Please let me know if I should change anything, I'll make sure to get it done before EOD Friday.

2023-05-05 04:29 UTC, BlazingAsher commented
I think you forgot to implement the hover/focused/pressed animations (a bubble appears around it), right now the link just becomes less opaque.

2023-05-05 18:33 UTC, whyismynamerudy commented
> I think you forgot to implement the hover/focused/pressed animations (a bubble appears around it), right now the link just becomes less opaque.

I fixed the varying of the link opacity; as for the bubble that appears around it, it is present but it not visible when you hover on it because the background color that's supposed to appear on hover is very similar to white and can't be seen well on a white background - if you click and hold the link, however, you can see that the pressed bubble appears with the right color. If there's any other issues please lmk I'll fix it ASAP.

2023-05-06 16:23 UTC, BlazingAsher requested changes

2023-05-06 16:23 UTC, BlazingAsher commented on src/components/Link/Link.module.scss
> +        background-color: rgba($color: #FFFBEB, $alpha: 0.12);
please use the alpha parameter of getColor instead of hard coding the color:
eg.
```
colors.getColor(warning-50, null, 0.12)
```

2023-05-06 16:23 UTC, BlazingAsher commented on src/components/Link/Link.module.scss
> +        background-color: rgba($color: #FDE68A, $alpha: 0.18);
same here, as above

2023-05-09 07:02 UTC, BlazingAsher approved these changes

2023-05-09 07:02 UTC, merged